sudo: required

language: cpp

services:
  - docker

before_install:
- docker pull sdt4docker/raspberry-pi-cross-compiler
- docker run sdt4docker/raspberry-pi-cross-compiler > rpxc
- chmod +x rpxc
- mv rpxc ~/bin/
- sudo apt-get update && sudo apt-get install -y libsdl2-dev
- cmake .

script: make
