language: cpp
sudo: false

compiler:
- gcc

os:
- linux
- osx

# LINUX
addons:
  apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
   - libsdl2-dev

# OSX
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi
  - cmake .

script: make
