language: cpp
sudo: false

compiler:
- gcc

os:
- linux
- osx

before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then apt-get update && apt-get install -y libsdl2-dev; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sdl2; fi
- cmake .

script: make
