language: cpp
sudo: required
dist: trusty

compiler:
- gcc

os:
- linux
- osx

before_install:
- ./scripts/setup.sh

# Hack around to get a RetroPie like environment
- |-
  if [ $TRAVIS_OS_NAME == linux ]; then
    # Enable graphics with xvfb
    # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
    sleep 3 # give xvfb some time to start

    # Downgrade to the same gcc/g++ version as RetroPie 3.6
    # http://askubuntu.com/a/26518
    sudo apt-get install -y gcc-4.7
    sudo apt-get install -y g++-4.7
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 10
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 10
  fi

script:
- ./scripts/build.sh

- if [ $TRAVIS_OS_NAME == osx ]; then ./scripts/test.sh; fi
# running the renderer in Travis only works for OSX at the moment, because the Travis Linux environment uses OpenGL ES 3 which makes our shaders fail with:
# 0:7(14): error: no precision specified this scope for type `vec2'
# 0:8(14): error: no precision specified this scope for type `vec3'
# terminate called after throwing an instance of 'Shader::ShaderCompileError'
#  what():  jw
# ./test.sh: line 7: 12471 Aborted                 (core dumped) ./a_retro_test
#
notifications:
  slack:
    secure: ojfqQEe/j+p+ZZk/F4RgzTRRTDJ0EjospQH/P999Pidq1nGhgMZfDwDQf5etxo0u+7JMPkkwt+YtHooZ2DaI443szIe/RGRTKwD/iB9quMm79psMRvrtFxCrgxF1FZbaw/XFdNQDkxGXDgY3dcVxRnrmhTWdmfdYirJuN2gAj+grhA3kKLYzakZB7OD4/Mbh//DnSR1RjtnoMXjCCLuFXRS2PKKO2e9PRZPECYzczHSnnP204XJRRc9f3b45DJ42kLV3Gnzdt+5qNVMZmuPWH+VnsLm1RXzQ7WX48UlKbfWGcicsbd96lD+QNVznEXhzLlgTADgeHBzPWhPx89vXK1SzCTWUXKTp8fglnY52H3aQQjGY3vUQBNMN7lMlJ3GE50BzvjU32qJ3YArZRqtaXXKdKWtLnfXPdLK7SMQpXWv8epr9kJWOVMTIEfqEZAiGU9na+OKkg6LpVkMDc9dxt6uyEyzrlKGTvF/35Dk7VGTthVe3r0ukPdrOjiFNr6iUYgDXYaUHN2oZDTPT93IUD26/2gaDKG1d4mcmEwIRdGU1obp1rAMgVUKHv90ZCv2wv71gut0ShY97UW6o9oGXTdQxMGb5X/evAET8yyxcVKVcIGDvVNuj2YvuOsgkQISHWgqLR5DzCJ+dnaJJqnGkA+Im46tHhliPYOBQsEM7sLY=
  email: false
