platform:
- x86

environment:
  matrix:

# VS 2015
  - BUILD_TYPE: cmake
    VS_VERSION: Visual Studio 14

shallow_clone: true

## We can't use our PowerShell convenience scripts because I couldn't
## get the errors to propagate properly even when adding "$host.SetShouldExit($LastExitCode)":
## https://www.appveyor.com/docs/build-configuration#script-blocks-in-build-configuration
## It would just say "Command executed with exception: " on error, which isn't good enough.
build_script:
  - echo build_script
  - echo "%platform% %VS_VERSION%"
  - cmake .
  - msbuild .\ALL_BUILD.vcxproj /m

test_script:
  - echo test_script
  - .\Debug\a_retro_test.exe

deploy: off

notifications:
  - provider: Slack
    incoming_webhook:
      secure: EFpQnafknWWQ215QQ3QOmXlw/CNwK7PL2qEv61nVukqFLrm7tiwn6t/29vYJd+XfkyhNmLhJFrF1TZksiVx2pg0eBXqnKGGnil3cjE7EK2k=
